package com.sollian.buz.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sollian.buz.bean.Article;
import com.sollian.buz.bean.Board;
import com.sollian.buz.bean.Favorite;
import com.sollian.buz.bean.User;
import com.sollian.buz.bean.Widget;
import com.sollian.buz.bean.Section;

import com.sollian.buz.bean.ArticleDao;
import com.sollian.buz.bean.BoardDao;
import com.sollian.buz.bean.FavoriteDao;
import com.sollian.buz.bean.UserDao;
import com.sollian.buz.bean.WidgetDao;
import com.sollian.buz.bean.SectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig boardDaoConfig;
    private final DaoConfig favoriteDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig widgetDaoConfig;
    private final DaoConfig sectionDaoConfig;

    private final ArticleDao articleDao;
    private final BoardDao boardDao;
    private final FavoriteDao favoriteDao;
    private final UserDao userDao;
    private final WidgetDao widgetDao;
    private final SectionDao sectionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        boardDaoConfig = daoConfigMap.get(BoardDao.class).clone();
        boardDaoConfig.initIdentityScope(type);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        widgetDaoConfig = daoConfigMap.get(WidgetDao.class).clone();
        widgetDaoConfig.initIdentityScope(type);

        sectionDaoConfig = daoConfigMap.get(SectionDao.class).clone();
        sectionDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        boardDao = new BoardDao(boardDaoConfig, this);
        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        widgetDao = new WidgetDao(widgetDaoConfig, this);
        sectionDao = new SectionDao(sectionDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(Board.class, boardDao);
        registerDao(Favorite.class, favoriteDao);
        registerDao(User.class, userDao);
        registerDao(Widget.class, widgetDao);
        registerDao(Section.class, sectionDao);
    }
    
    public void clear() {
        articleDaoConfig.clearIdentityScope();
        boardDaoConfig.clearIdentityScope();
        favoriteDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        widgetDaoConfig.clearIdentityScope();
        sectionDaoConfig.clearIdentityScope();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public BoardDao getBoardDao() {
        return boardDao;
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public WidgetDao getWidgetDao() {
        return widgetDao;
    }

    public SectionDao getSectionDao() {
        return sectionDao;
    }

}
